import { Preset } from '../types';

export const presets: Preset[] = [
  {
    id: 'sat-linear',
    name: 'SAT Linear Function',
    description: 'Standard SAT-style linear function graph',
    category: 'SAT',
    config: {
      axisConfig: {
        xMin: -5,
        xMax: 5,
        yMin: -5,
        yMax: 5,
        xStep: 1,
        yStep: 1,
        showGrid: true,
        showMinorGrid: false,
        showNumbers: true,
        showAxisLabels: false,
        xLabel: 'x',
        yLabel: 'y',
      },
      style: {
        backgroundColor: '#ffffff',
        axisColor: '#000000',
        gridColor: '#d0d0d0',
        minorGridColor: '#f0f0f0',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        lineWidth: 2,
      },
    },
  },
  {
    id: 'sat-quadratic',
    name: 'SAT Quadratic Function',
    description: 'SAT-style parabola graph',
    category: 'SAT',
    config: {
      axisConfig: {
        xMin: -6,
        xMax: 6,
        yMin: -2,
        yMax: 10,
        xStep: 2,
        yStep: 2,
        showGrid: true,
        showMinorGrid: false,
        showNumbers: true,
        showAxisLabels: false,
        xLabel: 'x',
        yLabel: 'y',
      },
      style: {
        backgroundColor: '#ffffff',
        axisColor: '#000000',
        gridColor: '#d0d0d0',
        minorGridColor: '#f0f0f0',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        lineWidth: 2,
      },
    },
  },
  {
    id: 'act-standard',
    name: 'ACT Standard Grid',
    description: 'Standard ACT coordinate plane',
    category: 'ACT',
    config: {
      axisConfig: {
        xMin: -8,
        xMax: 8,
        yMin: -8,
        yMax: 8,
        xStep: 2,
        yStep: 2,
        showGrid: true,
        showMinorGrid: false,
        showNumbers: true,
        showAxisLabels: true,
        xLabel: 'x',
        yLabel: 'y',
      },
      style: {
        backgroundColor: '#ffffff',
        axisColor: '#000000',
        gridColor: '#cccccc',
        minorGridColor: '#eeeeee',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        lineWidth: 2,
      },
    },
  },
  {
    id: 'ap-calculus',
    name: 'AP Calculus',
    description: 'AP Calculus exam style graph',
    category: 'AP',
    config: {
      axisConfig: {
        xMin: -4,
        xMax: 4,
        yMin: -3,
        yMax: 3,
        xStep: 1,
        yStep: 1,
        showGrid: true,
        showMinorGrid: true,
        showNumbers: true,
        showAxisLabels: true,
        xLabel: 'x',
        yLabel: 'y',
      },
      style: {
        backgroundColor: '#ffffff',
        axisColor: '#000000',
        gridColor: '#c0c0c0',
        minorGridColor: '#e8e8e8',
        fontSize: 10,
        fontFamily: 'Times New Roman, serif',
        lineWidth: 1.5,
      },
    },
  },
  {
    id: 'trig-unit-circle',
    name: 'Trigonometry Unit Circle',
    description: 'Unit circle for trigonometric functions',
    category: 'General',
    config: {
      axisConfig: {
        xMin: -1.5,
        xMax: 1.5,
        yMin: -1.5,
        yMax: 1.5,
        xStep: 0.5,
        yStep: 0.5,
        showGrid: true,
        showMinorGrid: false,
        showNumbers: true,
        showAxisLabels: true,
        xLabel: 'x',
        yLabel: 'y',
      },
      style: {
        backgroundColor: '#ffffff',
        axisColor: '#000000',
        gridColor: '#d0d0d0',
        minorGridColor: '#f0f0f0',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        lineWidth: 2,
      },
    },
  },
  {
    id: 'wide-view',
    name: 'Wide View',
    description: 'Large coordinate plane for complex functions',
    category: 'General',
    config: {
      axisConfig: {
        xMin: -20,
        xMax: 20,
        yMin: -20,
        yMax: 20,
        xStep: 5,
        yStep: 5,
        showGrid: true,
        showMinorGrid: true,
        showNumbers: true,
        showAxisLabels: true,
        xLabel: 'x',
        yLabel: 'y',
      },
      style: {
        backgroundColor: '#ffffff',
        axisColor: '#000000',
        gridColor: '#d0d0d0',
        minorGridColor: '#f0f0f0',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        lineWidth: 2,
      },
    },
  },
];

export function getPresetById(id: string): Preset | undefined {
  return presets.find((preset) => preset.id === id);
}

export function getPresetsByCategory(category: Preset['category']): Preset[] {
  return presets.filter((preset) => preset.category === category);
}
